apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0-infra-main
  namespace: argocd-infra
spec:
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /operation
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: argocd-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - repoURL: 'https://github.com/GoodHelmCharts/argocd-applications.git' #var_git_chart_argocd_app
      path: ./
      targetRevision: "dev"
      helm:
        valueFiles:
          - values.yaml
          # ARGOCD
          - $templates/argocd/argocd-simple.yaml
          - $templates/argocd/argocd-lookup.yaml
          - $templates/argocd/argocd-apps.yaml
        valuesObject:
          apps_values:
            argocd:
              domain: .kind
            argocd-apps:
              repoURL: 'https://github.com/k8s-cd/kind-framework-12.git' #var_git_k8s_cd
    - repoURL: 'https://github.com/GoodInfras/argocd-templates.git' #var_git_argocd_templates
      targetRevision: "HEAD"
      ref: templates
